### ISSUE TITLE
Build failure with nginx 1.7.9

### ISSUE THREAD

**Issue by jbergstroem** [yaoweibin/nginx_ajp_module#33]
There's been some refactoring of the upstream module data types (well, more than that), which makes the build fail:
```
nginx_ajp_module-0.3.0/ngx_http_ajp_module.c:870:53: error: invalid type argument of '->' (have 'int')
     if (conf->upstream.cache && conf->upstream.cache->data == NULL) {
 ```

**Comment by jbergstroem** [comment]
fwiw, this applies to 1.7.10 as well.

**Comment by yaoweibin** [comment]
I have fixed the compatible problem. Try the latest revision in the master branch.

Thanks.
