### ISSUE TITLE
Unable to upload files more than 4 GB with Nginx AJP module

### ISSUE THREAD

**Issue by sumitkumarn** [yaoweibin/nginx_ajp_module#46]
I am using Nginx with tomcat on windows. Unable to upload files more than 4 GB and the Nginx error log shows the following error "WSASend() failed (10053: An established connection was aborted by the software in your host machine) while sending request body again to upstream".

Please update if anyone has the solution for this.

**Comment by yaoweibin** [comment]
This module is no updated. You may use the stream module instead.
